const API_URL="http://localhost:8080"

export const SIGNUP_POST_ENDPOINT= API_URL+"/usuario"
export const SIGNIN_POST_ENDPOINT= API_URL+"/usuario/login"
export const MISCITAS_GET_ENDPOINT= API_URL+"/usuario/miscitas"
export const CREARCITA_POST_ENDPOINT= API_URL+"/cita"
export const CITASCREADAS_GET_ENDPOINT= API_URL+"/cita"
export const CITADETALLE_GET_ENDPOINT= API_URL+"/cita"
export const ELIMINARCITA_DELETE_ENDPOINT= API_URL+"/cita"
export const ACTUALIZARCITA_PUT_ENDPOINT= API_URL+"/cita"